HTTP/1.1 200 OK
Server: openresty
Date: Fri, 09 Jun 2023 14:08:45 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 2650
Connection: close
X-Cache-Key: /geo/1.0/direct?limit=1&q=london,,gb
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST

[
  {
    "name": "London",
    "local_names": {
      "wo": "Londar",
      "or": "ଲଣ୍ଡନ",
      "fy": "Londen",
      "ps": "لندن",
      "ml": "ലണ്ടൻ",
      "ar": "لندن",
      "an": "Londres",
      "co": "Londra",
      "nn": "London",
      "ia": "London",
      "ht": "Lonn",
      "lv": "Londona",
      "ro": "Londra",
      "ur": "علاقہ لندن",
      "id": "London",
      "tg": "Лондон",
      "ru": "Лондон",
      "da": "London",
      "ie": "London",
      "sc": "Londra",
      "se": "London",
      "sm": "Lonetona",
      "zh": "伦敦",
      "lb": "London",
      "ig": "London",
      "sw": "London",
      "ba": "Лондон",
      "cu": "Лондонъ",
      "bg": "Лондон",
      "mr": "लंडन",
      "ja": "ロンドン",
      "ta": "இலண்டன்",
      "ce": "Лондон",
      "eu": "Londres",
      "sh": "London",
      "is": "London",
      "bs": "London",
      "pl": "Londyn",
      "hi": "लंदन",
      "it": "Londra",
      "af": "Londen",
      "et": "London",
      "gu": "લંડન",
      "cy": "Llundain",
      "gn": "Lóndyre",
      "gv": "Lunnin",
      "eo": "Londono",
      "ln": "Lóndɛlɛ",
      "ca": "Londres",
      "sn": "London",
      "bn": "লন্ডন",
      "sk": "Londýn",
      "nv": "Tooh Dineʼé Bikin Haalʼá",
      "sd": "لنڊن",
      "bo": "ལོན་ཊོན།",
      "kl": "London",
      "sl": "London",
      "av": "Лондон",
      "sa": "लन्डन्",
      "hu": "London",
      "br": "Londrez",
      "vo": "London",
      "bm": "London",
      "oc": "Londres",
      "ny": "London",
      "fa": "لندن",
      "ee": "London",
      "tw": "London",
      "mk": "Лондон",
      "ga": "Londain",
      "no": "London",
      "el": "Λονδίνο",
      "te": "లండన్",
      "es": "Londres",
      "wa": "Londe",
      "na": "London",
      "uz": "London",
      "en": "London",
      "st": "London",
      "hy": "Լոնդոն",
      "mt": "Londra",
      "ascii": "London",
      "so": "London",
      "kk": "Лондон",
      "my": "လန်ဒန်မြို့",
      "cv": "Лондон",
      "az": "London",
      "pt": "Londres",
      "uk": "Лондон",
      "mn": "Лондон",
      "lt": "Londonas",
      "ne": "लन्डन",
      "gd": "Lunnainn",
      "fi": "Lontoo",
      "jv": "London",
      "tr": "Londra",
      "cs": "Londýn",
      "gl": "Londres",
      "kw": "Loundres",
      "mi": "Rānana",
      "ka": "ლონდონი",
      "feature_name": "London",
      "fo": "London",
      "io": "London",
      "am": "ለንደን",
      "mg": "Lôndôna",
      "rm": "Londra",
      "tl": "Londres",
      "ms": "London",
      "fr": "Londres",
      "ky": "Лондон",
      "be": "Лондан",
      "ug": "لوندۇن",
      "yo": "Lọndọnu",
      "tt": "Лондон",
      "ay": "London",
      "ha": "Landan",
      "sr": "Лондон",
      "bh": "लंदन",
      "sv": "London",
      "vi": "Luân Đôn",
      "lo": "ລອນດອນ",
      "ff": "London",
      "tk": "London",
      "si": "ලන්ඩන්",
      "hr": "London",
      "zu": "ILondon",
      "th": "ลอนดอน",
      "km": "ឡុងដ៍",
      "ko": "런던",
      "pa": "ਲੰਡਨ",
      "kv": "Лондон",
      "os": "Лондон",
      "fj": "Lodoni",
      "he": "לונדון",
      "nl": "Londen",
      "kn": "ಲಂಡನ್",
      "ku": "London",
      "su": "London",
      "to": "Lonitoni",
      "ab": "Лондон",
      "bi": "London",
      "om": "Landan",
      "sq": "Londra",
      "de": "London",
      "li": "Londe",
      "yi": "לאנדאן",
      "qu": "London"
    },
    "lat": 51.5073219,
    "lon": -0.1276474,
    "country": "GB",
    "state": "England"
  }
]
